#!/command/with-contenv bash
# shellcheck shell=bash

exec \
    s6-notifyoncheck -d -n 300 -w 1000 -c "nc -z localhost 10400" \
        s6-setuidgid abc python3 -m wyoming_openwakeword \
        --uri 'tcp://0.0.0.0:10400' \
        --preload-model "${PRELOAD_MODEL:ok_nabu}" \
        --custom-model-dir /config/custom-models
